language: node_js
os: linux
dist: trusty

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm
  # const
  - export PACKAGE_NAME=$(node -p "require('./package.json').name")
  - export PACKAGE_VERSION=$(node -p "require('./package.json').version")
  - export SONAR_VERSION=${PACKAGE_VERSION}-b${TRAVIS_BUILD_ID}-${TRAVIS_BRANCH}
  - export NODE_VERSION=$(node --version)
  - export NPM_VERSION=$(npm --version)

  # logging
  - npm --version || echo npm not installed
  - node --version || echo node not installed
  - echo "package version $PACKAGE_VERSION"

stages:
  - build
  - test
  - release

jobs:
  include:

    # Job: Build
    - stage: build
      node_js:
        - 'lts/*'
      script:
        - npm run build
    # Job: Test
    - stage: test
      node_js:
        - 'lts/*'
      script:
        - npm run test -- --coverage --runInBand
        - npm run flow || echo "Skipping npm run flow, see https://github.com/jamiebuilds/react-loadable/pull/216#issuecomment-566027008)"

    # Job: Release
    - stage: release
#      if: branch = master AND type = push AND fork = false
      if: branch = master AND type = push
      node_js:
        - 'lts/*'
      script:
        - npm run build
        - npx semantic-release
